### ISSUE TITLE
Incompatible with phoenix_html 3.0.0

### ISSUE THREAD

**Issue by fceruti** [elixirstatus/phoenix_html_sanitizer#5]
I'm trying to update to use phoenix 1.6, and I'm running into this issue.

```
Failed to use "phoenix_html" (versions 3.0.0 to 3.0.4) because
  phoenix_html_sanitizer (versions 1.0.0 to 1.0.2) requires ~> 2.0
```

**Comment by rrrene** [comment]
Thx for reporting this! :+1: It should be be fixed in the latest version (`1.1.1`).

If it is not, please feel free to re-open this issue!
