### ISSUE TITLE
Updating package to 1.1.1 downgraded dependency html_sanitize_ex from 1.4.1 to 1.3.0

### ISSUE THREAD

**Issue by Sinc63** [elixirstatus/phoenix_html_sanitizer#6]
I noticed while comparing old and new mix.lock files that although I upgraded this package, it caused a downgrade in the nested dependency. This is because way back, 6 years ago, the dependency was changed from 2 parts (~1.1) to 3 parts (~1.3.0), so we no longer get the 1.4.1 version of the html_sanitize_ex package.

I can't tell, but this is perhaps unintentional and you may want to revert the html_sanitize_ex version back to 1.1 so that it will take 1.4. Or change it to 1.4 explicitly.

I can work around this if I decide it's useful, by adding an override in my own mix.exs, but it would be nice to know what the owner's view is.

**Comment by Sinc63** [comment]
Please also change "deps: deps" to "deps: deps()". It seems that with the latest version of something (maybe hex) it is a terminal error despite just saying warning.

**Comment by rrrene** [comment]
This is now part of `v1.2.0`. Sorry for the delay 🙏
